### ISSUE TITLE
[DevOps]   k8s的自动触发构建

### ISSUE THREAD

**Issue by yangyaodong1** [zeyangli/devops_tickets_repo#2]
> Hi, 一般问题处理的过程是: 提交issues指派给zeyangli, 看到问题会及时的反馈和回复. 更详细的错误信息更有助于更快且更准确的定位问题。
 
#### 1.问题详细描述[必填]
![image](https://github.com/zeyangli/devops_tickets_repo/assets/152180844/0d6268f7-d33b-4c78-bb94-abe6c5c3ccde)
![image](https://github.com/zeyangli/devops_tickets_repo/assets/152180844/971541df-9797-492e-b9b2-298537b70a9c)

#### 2.自行排查结果[必填]
该检查的都检查了，未果
#### 3.需要得到的帮助[可选]
为什么连代码都没有clone到，我本地测试git没有问题，网络也没问题

> 注释：提交工单后，1-3个工作日内会有初步的响应。

**Comment by zeyangli** [comment]
参考解决方法：
1. 由于你配置的是动态的jenkins agent节点， 你可以在Jenkinsfile中添加sleep 步骤，然后kubectl exec进入pod中手动运行git 命令测试。 
2. 通常git clone:  the remote end hung up错误提示可能是由于网络问题导致。 根据之前的经验判断，如果确认网络没问题检查下git客户端（动态agent节点内的git客户端）的版本号，估计要升级到2.0以上。

**Comment by yangyaodong1** [comment]
问题已解决，原因：我动态slave的容器无法通行gitlab，感谢

**Comment by zeyangli** [comment]
Ok， 问题已解决我们将关闭此issue， 如果后面还有此问题可以reopen重新打开这个issue.
