### ISSUE TITLE
课程中是否含有argo cd客户端工具发布应用教程

### ISSUE THREAD

**Issue by lipengbo-cloud** [zeyangli/devops_tickets_repo#3]
> Hi, 一般问题处理的过程是: 提交issues指派给zeyangli, 看到问题会及时的反馈和回复. 更详细的错误信息更有助于更快且更准确的定位问题。
 
#### 1.问题详细描述[必填]
我们这边不想借助其他工具，比如 kubectl、helm、kustomize，不借助这些工具情况下，直接使用编写好的YAML资源清单，能部署应用吗？

另外，您课程中有讲，怎么使用argo cd的命令行发布应用吗，我们这边是gitlab CI想配合argo cd 优化优化我们最后的部署过程

#### 3.需要得到的帮助[可选]
我需要配合gitlab ci+argo cd的组合，在gitlab ci触发流水线后，到部署阶段，可以使用argo cd命令行的方式去部署应用
不需要借助kubectl、helm、kustomize这些工具去完成部署

> 注释：提交工单后，1-3个工作日内会有初步的响应。

**Comment by zeyangli** [comment]
Hi,
1. 当使用了argocd之后就不需要再用这些（kubectl、helm、kustomize）命令行工具了，argocd已经内置了这些工具功能。
2. Argocd有命令行的，一般CI构建完镜像后，CD阶段可以通过argocd CLI命令行触发应用的同步。当然第一次需要创建argocd应用后面可以直接触发同步，这块儿的逻辑可以自己实现。

参考ArgoCD实践文档：
- argocd project：  https://www.yuque.com/devopsgroup/argo/rygwwblm5yr1cdmx
- argocd 发布helm，kustomize示例： https://www.yuque.com/devopsgroup/argo/npgsq0gwfg1b9g0a

**Comment by zeyangli** [comment]
补充常用的argocd命令行，以下是 argocd 命令行工具中常用的一些命令和参数：

- argocd login：

用于登录到 Argo CD 服务器。
参数：argocd login <ARGOCD_SERVER>，其中 <ARGOCD_SERVER> 是 Argo CD 服务器的地址。

- argocd logout：

用于注销当前登录的 Argo CD 会话。
参数：无。

- argocd app create：

用于创建一个新的应用程序。
参数：argocd app create <APP_NAME> --repo <REPO_URL> --path <REPO_PATH> --dest-namespace <NAMESPACE>，其中 <APP_NAME> 是应用程序的名称，<REPO_URL> 是应用程序的 Git 存储库 URL，<REPO_PATH> 是存储库中应用程序的路径，<NAMESPACE> 是目标 Kubernetes 命名空间。


- argocd app get：

用于获取应用程序的详细信息。
参数：argocd app get <APP_NAME>，其中 <APP_NAME> 是应用程序的名称。

- argocd app list：

用于列出所有应用程序。
参数：无。

- argocd app sync：

用于同步应用程序的状态。
参数：argocd app sync <APP_NAME>，其中 <APP_NAME> 是应用程序的名称。

- argocd app delete：

用于删除应用程序。
参数：argocd app delete <APP_NAME>，其中 <APP_NAME> 是应用程序的名称。

- argocd app set：

用于设置应用程序的属性。
参数：argocd app set <APP_NAME> --parameter <PARAMETER_NAME>=<PARAMETER_VALUE>，其中 <APP_NAME> 是应用程序的名称，<PARAMETER_NAME> 是要设置的参数名称，<PARAMETER_VALUE> 是参数的值。

这只是一些常用的 argocd 命令和参数示例，argocd 提供了更多功能和选项，可以通过 argocd --help 命令查看完整的命令和参数列表，以及它们的说明和用法。

**Comment by lipengbo-cloud** [comment]
好的，感谢老师给的思路，我去尝试下

**Comment by zeyangli** [comment]
Ok， 问题已解决我们将关闭此issue， 如果后面还有此问题可以reopen重新打开或者新建issue.
